name: SMCH
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161616'
    - '#a2a2a2'
    - '#615137'
    - '#369f7e'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.9291027013678104
purpose: []
