name: SMCH
favicon: null
layout_spectrum: 0.45437
typography_spectrum: 0.06413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d1d1'
    - '#014455'
    - '#41e8e2'
    - '#e8a300'
    - '#0092a8'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
