name: SMCH
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d1d1'
    - '#014455'
    - '#41e8e2'
    - '#e8a300'
    - '#0092a8'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
